# Generated by Django 4.0.5 on 2022-06-17 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_door_infomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_infomation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opener', to=settings.AUTH_USER_MODEL),
        ),
    ]
