# Generated by Django 4.0.5 on 2022-06-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_door_infomation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_infomation',
            name='img_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
