# Generated by Django 4.0.5 on 2022-06-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_door_infomation_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door_infomation',
            name='img_url',
        ),
    ]
